project:
  type: website
  output-dir: docs   

website:
  title: "street_canyons"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: maps/canyons.html
        text: interactive map
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



